workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Check and recreate iOS project files
        script: |
          echo "Checking iOS project structure..."
          cd $CM_BUILD_DIR
          pwd
          ls -la ios/ || echo "ios directory not found"
          
          # Check if project.pbxproj exists
          if [ ! -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
            echo "⚠️ iOS project.pbxproj missing, recreating iOS files..."
            flutter create --platforms=ios .
            echo "✅ iOS project files recreated"
          else
            echo "✅ iOS project.pbxproj exists"
          fi
          
          # Verify project structure
          if [ -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
            echo "✅ project.pbxproj verified"
            ls -la ios/Runner.xcodeproj/
          else
            echo "❌ project.pbxproj still missing after recreation"
            exit 1
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

